{
    "name": "Create Product",
    "version": "0.1",
    "summary": "The right way to create a product in Odoo",
    "author": "Ing. Diego Venegas",
    "website": "https://www.google.com",
    "description": "Module to create a product, in a formatted and correct way",
    "category": "Sales/Sales",
    "license": "AGPL-3",
    "depends": ["base", "product", "stock", "account"],
    "data": [
        "security/ir.model.access.csv",
        "views/product_create_view.xml",
        "views/product_size_view.xml",
        "views/product_type_view.xml",
    ],
    "installable": True,
    "application": False,
    "auto_install": False,
}
