# -*- coding: utf-8 -*-
from odoo import models, fields, api
from odoo.exceptions import ValidationError


class ActivoFijoTraslado(models.Model):
    _name = "activo.fijo.traslado"
    _description = "Fixed Asset Transfer"
    _inherit = ["mail.thread", "mail.activity.mixin"]
    _order = "fecha desc"

    name = fields.Char(string="Name", compute="_compute_name", store=True)
    activo_id = fields.Many2one(
        "activo.fijo", string="Asset", required=True, ondelete="cascade", tracking=True
    )
    activo_folio = fields.Char(
        related="activo_id.name", string="Folio", readonly=True, store=True
    )

    fecha = fields.Date(
        string="Transfer Date",
        required=True,
        default=fields.Date.context_today,
        tracking=True,
    )

    origen_responsable_id = fields.Many2one(
        "res.users", string="Previous Responsible", tracking=True
    )
    destino_responsable_id = fields.Many2one(
        "res.users", string="New Responsible", tracking=True
    )

    origen_almacen_id = fields.Many2one(
        "stock.warehouse", string="Previous Warehouse", tracking=True
    )
    destino_almacen_id = fields.Many2one(
        "stock.warehouse", string="New Warehouse", tracking=True
    )

    motivo = fields.Text(string="Transfer Reason", required=True)

    @api.depends("activo_id", "fecha")
    def _compute_name(self):
        for record in self:
            if record.activo_id and record.fecha:
                record.name = f"Transfer - {record.activo_id.name} - {record.fecha}"
            elif record.activo_id:
                record.name = f"Transfer - {record.activo_id.name}"
            else:
                record.name = "New Transfer"

    @api.onchange("activo_id")
    def _onchange_activo_id(self):
        """Auto-fill origin fields when an asset is selected"""
        if self.activo_id:
            self.origen_responsable_id = self.activo_id.responsable_id
            self.origen_almacen_id = self.activo_id.almacen_id

    @api.model
    def create(self, vals):
        # Capture origin values from the asset BEFORE creating the record
        # to ensure they are saved in the database
        if vals.get("activo_id"):
            activo = self.env["activo.fijo"].browse(vals["activo_id"])
            if activo:
                # Only fill origin fields if they are not already in vals
                if not vals.get("origen_responsable_id") and activo.responsable_id:
                    vals["origen_responsable_id"] = activo.responsable_id.id
                if not vals.get("origen_almacen_id") and activo.almacen_id:
                    vals["origen_almacen_id"] = activo.almacen_id.id

        record = super().create(vals)

        # Mark previous accountabilities of the origin responsible as transferred
        if record.origen_responsable_id:
            responsivas_anteriores = self.env["activo.fijo.responsiva"].search(
                [
                    ("activo_id", "=", record.activo_id.id),
                    ("responsable_id", "=", record.origen_responsable_id.id),
                    ("estado", "=", "vigente"),
                ]
            )
            if responsivas_anteriores:
                responsivas_anteriores.write({"estado": "transferida"})

        # Update the asset with the new destination values
        if record.destino_responsable_id:
            record.activo_id.responsable_id = record.destino_responsable_id
            # Update department with the responsible's department
            if record.destino_responsable_id.department_id:
                record.activo_id.departamento_id = (
                    record.destino_responsable_id.department_id
                )

        if record.destino_almacen_id:
            record.activo_id.almacen_id = record.destino_almacen_id

        # Change the asset status to "transferred"
        record.activo_id.estado = "transferido"

        # Create new accountability for the new responsible
        if record.destino_responsable_id:
            self.env["activo.fijo.responsiva"].with_context(
                skip_pdf_generation=True
            ).create(
                {
                    "activo_id": record.activo_id.id,
                    "responsable_id": record.destino_responsable_id.id,
                    "fecha_asignacion": record.fecha,
                    "estado": "vigente",
                    "observaciones": f"Accountability automatically generated by transfer. Reason: {record.motivo}",
                }
            )

        return record
